---
title: "Minimizing Regret in Life: Strategies for Making Better Decisions"
author: "Sampath Kovvali"
date: "2023-04-25"
categories: [Psychology]
---

> **"Our brain perceives the outside world through sensors such as the ears and eyes. Therefore, we are the output of a function that is determined by the inputs we receive and the initial conditions that exist."** - Scientists

When starting a project or any work, many people may fail partially or completely. Frustration and anger are forms of thinking induced by the brain to solve this problem. However, some people may end up thinking in loops and not completing the task, often making excuses. This is due to a part of the brain predicting that the work is not worthy. On the other hand, those who solve the problem or complete the task are often attributed to hard work and talent. This is partially correct and is often called survivorship bias. The failures may live with regrets and excuses. So how can we plan for the future while keeping these outcomes in mind? It’s not straightforward, but we can learn from psychology, computer science, and from children and older people.

## Food and Phycial Activity
The human brain is designed and optimized to survive in the wild. It tries all the easy ways to complete a task, and the first one is often not to try. For example, let’s say you planned to go to the gym in the morning but failed to get up. This is because the outcome of going to the gym - getting in shape and being strong mentally and physically - is delayed gratification. Our brain knows this information and may give up for the sake of sleep for short-term outcomes because it knows that the outcome may not happen due to the changing world around us. Remember, we are optimized to spend as little energy as possible.

Another example is planning a healthy diet but failing to stick to it and eating junk food instead. This happens because our brain predicts that a high-calorie diet is rare due to sugar, fats, and processed foods being new to humans when compared to the time scale of evolution. Getting high sugar and fat was key to survival back then, but these days it’s as free as beer, so our brain tells us to eat it.

## Internet
The internet has undoubtedly changed the way we interact with each other. While it has made communication easier and more convenient, it has also had negative effects on people's relationships. One of the most significant impacts is that it has decreased face-to-face interactions. Instead of meeting in person, people are increasingly communicating through messaging apps and social media. This can lead to a lack of emotional connection and a decrease in empathy. Additionally, the internet has made it easier to hide behind screens and say things that one would not say in person, leading to misunderstandings and conflicts. One of the main issues is that the internet provides instant gratification, which can lead to impatience and a decreased ability to delay gratification and work towards longer-term rewards. The constant stream of notifications and updates can also be overwhelming and distracting, leading to a lack of focus and presence in our real-life relationships.


## Make a plan

The first step in achieving your goals is to be aware of the fundamentals of life, such as diet, physical activity, finance, family, and friends. Start by thinking about how to optimize these parameters and then plan accordingly. Once you have established a strong foundation in these areas, you can pursue your passions and achieve your goals more easily. This information is available in many books, both physical and digital, and I recommend starting with physical books for a better reading experience.

### Book recomndations
- [Atomic Habits](https://jamesclear.com/atomic-habits) by James Clear
- [Ikigai: The Japanese Secret to a Long and Happy Life](https://www.goodreads.com/book/show/40534545-ikigai) by Héctor García and Francesc Miralles
- [Algorithms to Live By: The Computer Science of Human Decisions](https://algorithmstoliveby.com/) by Brian Christian and Tom Griffiths